services:
  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686"     # Jaeger UI
      - "14268:14268"     # Collector HTTP endpoint
      - "6831:6831/udp"   # Agent compact thrift (optional)
      - "6832:6832/udp"   # Agent binary thrift (optional)

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

